apiVersion: v1
kind: Pod
metadata:
  name:  two-tier-app-pod
spec:
  containers:
    - name: two-tier-app-ctr
      image: abhidocker948/flaskapp:latest
      env:
       - name: MYSQL_HOST
         value: "10.108.105.142"
       - name: MYSQL_USER
         value: "admin"
       - name: MYSQL_PASSWORD
         value: "admin"
       - name: MYSQL_DB
         value: "my-db"
      ports:
       - containerPort: 5000
      imagePullPolicy: Always